import auth_service
import order_service
import product_repository
import report_repository
import user_repository


get_todos_produtos = product_repository.get_todos_produtos
get_produto_por_id = product_repository.get_produto_por_id
criar_produto = product_repository.criar_produto
atualizar_produto = product_repository.atualizar_produto
deletar_produto = product_repository.deletar_produto
buscar_produtos = product_repository.buscar_produtos

get_todos_usuarios = user_repository.get_todos_usuarios
get_usuario_por_id = user_repository.get_usuario_por_id
criar_usuario = user_repository.criar_usuario
login_usuario = auth_service.login_usuario

criar_pedido = order_service.criar_pedido
get_pedidos_usuario = order_service.get_pedidos_usuario
get_todos_pedidos = order_service.get_todos_pedidos
atualizar_status_pedido = order_service.atualizar_status_pedido

relatorio_vendas = report_repository.relatorio_vendas
